import os
import json
from groq import Groq

_client = None


def _get_client():
    global _client
    if _client is None:
        _client = Groq(api_key=os.environ["GROQ_API_KEY"])
    return _client


SYSTEM_PROMPT = """You are an expert at detecting whether text was written by a human or generated by an AI tool.

Analyze the provided text and return a JSON object with exactly these fields:
- "ai_probability": a float between 0.0 and 1.0 (0.0 = definitely human, 1.0 = definitely AI)
- "reasoning": a brief one-sentence explanation of the strongest signal you observed

Look for: hedging phrases overused by AI ("it's worth noting", "in conclusion", "it is important to"),
unusually balanced paragraph structure, formal register in casual contexts, lack of personal voice,
templated transitions, and absence of the small inconsistencies natural to human writing.

Return ONLY valid JSON, no other text."""


def score(text: str) -> dict:
    """Return {"ai_probability": float, "reasoning": str}."""
    client = _get_client()
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": f"Analyze this text:\n\n{text}"},
        ],
        temperature=0.1,
        max_tokens=200,
    )
    raw = response.choices[0].message.content.strip()
    try:
        result = json.loads(raw)
        ai_prob = float(result.get("ai_probability", 0.5))
        ai_prob = max(0.0, min(1.0, ai_prob))
        reasoning = str(result.get("reasoning", ""))
        return {"ai_probability": ai_prob, "reasoning": reasoning}
    except (json.JSONDecodeError, KeyError, ValueError):
        return {"ai_probability": 0.5, "reasoning": "Could not parse LLM response."}
