from pipeline import llm_signal, stylometry, burstiness

# Signal weights — must sum to 1.0
WEIGHTS = {"llm": 0.50, "stylo": 0.25, "burst": 0.25}

# Label thresholds
THRESHOLD_HUMAN = 0.40
THRESHOLD_AI = 0.73

LABEL_HUMAN = {
    "verdict": "Likely written by a human.",
    "explanation": (
        "Our analysis found strong indicators of human authorship in this piece."
    ),
    "confidence_note": (
        "If you believe this label is incorrect, you may submit an appeal."
    ),
}

LABEL_AI = {
    "verdict": "Likely AI-generated.",
    "explanation": (
        "Our analysis found strong indicators that this content was generated "
        "by an AI tool."
    ),
    "confidence_note": (
        "Creators who believe this is a mistake can submit an appeal — "
        "misclassification happens, and every appeal is reviewed."
    ),
}

LABEL_UNCERTAIN = {
    "verdict": "Authorship unclear.",
    "explanation": (
        "Our system could not confidently determine whether this content was "
        "written by a human or generated by AI. This label does not mean the "
        "content is AI-generated — it means we don't have enough signal to say "
        "either way."
    ),
    "confidence_note": (
        "If you're the creator, you can submit an appeal to have this reviewed."
    ),
}


def _combine(llm_prob: float, stylo_prob: float, burst_result: dict) -> float:
    """Weighted average; if burstiness is unreliable, redistribute its weight."""
    if not burst_result.get("reliable", True):
        w_llm = WEIGHTS["llm"] / (WEIGHTS["llm"] + WEIGHTS["stylo"])
        w_stylo = WEIGHTS["stylo"] / (WEIGHTS["llm"] + WEIGHTS["stylo"])
        return w_llm * llm_prob + w_stylo * stylo_prob

    burst_prob = burst_result["ai_probability"]
    return (
        WEIGHTS["llm"] * llm_prob
        + WEIGHTS["stylo"] * stylo_prob
        + WEIGHTS["burst"] * burst_prob
    )


def _label(score: float) -> dict:
    if score < THRESHOLD_HUMAN:
        return LABEL_HUMAN
    if score >= THRESHOLD_AI:
        return LABEL_AI
    return LABEL_UNCERTAIN


def _attribution(score: float) -> str:
    if score < THRESHOLD_HUMAN:
        return "human"
    if score >= THRESHOLD_AI:
        return "ai"
    return "uncertain"


def run(text: str) -> dict:
    """Run the full three-signal pipeline and return a complete decision record."""
    llm_result = llm_signal.score(text)
    stylo_result = stylometry.score(text)
    burst_result = burstiness.score(text)

    llm_prob = llm_result["ai_probability"]
    stylo_prob = stylo_result["ai_probability"]

    combined = _combine(llm_prob, stylo_prob, burst_result)
    combined = round(combined, 4)

    label = _label(combined)
    attribution = _attribution(combined)

    confidence_pct = round(
        (1.0 - abs(combined - 0.5) * 2) * 100
        if attribution == "uncertain"
        else abs(combined - 0.5) * 2 * 100,
        1,
    )

    return {
        "attribution": attribution,
        "confidence": combined,
        "confidence_pct": confidence_pct,
        "label": {
            "verdict": label["verdict"],
            "explanation": label["explanation"],
            "confidence_note": label["confidence_note"],
            "confidence_display": f"Confidence: {confidence_pct}%",
        },
        "signals": {
            "llm_score": round(llm_prob, 4),
            "llm_reasoning": llm_result.get("reasoning", ""),
            "stylometric_score": round(stylo_prob, 4),
            "stylometric_features": stylo_result.get("features", {}),
            "burstiness_score": round(burst_result["ai_probability"], 4),
            "burstiness_cov": burst_result.get("coefficient_of_variation"),
            "burstiness_reliable": burst_result.get("reliable", True),
        },
    }
